import Link from "next/link";
import "./globals.css";
import { NextAuthProvider } from "./providers";
import {ZComponent} from "@/components/z";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Link href={"/"}>Home</Link>
				<Link href={"/home"}>Home 2</Link>
				<Link href={"/about"}>About</Link>
				<ZComponent />
				<NextAuthProvider>{children}</NextAuthProvider>
			</body>
		</html>
	);
}
